git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  windowSize: "nomarl"
  nerdFontsVersion: "3"
  sidePanelWidth: 0.25
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
  branchColors:
    "fix": "#11aaff"
    "feat": "#ffaa11"
refresher:
  refreshInterval: 3
os:
  editCommand: "nvim"
customCommands:
  - key: "C"
    context: "files"
    command: "git commit -v -t ~/.config/git/commit_template_with_prompt_japanese.txt"
    description: "Commit changes using git editor"
    subprocess: true
