git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  windowSize: "nomarl"
  nerdFontsVersion: "3"
  sidePanelWidth: 0.15
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
  branchColors:
    "fix": "#11aaff"
    "feat": "#ffaa11"
refresher:
  refreshInterval: 3
os:
  editCommand: "nvim"
